### ISSUE TITLE
exceptions

### ISSUE THREAD

**Issue by wx4cb** [andreiciubotariu/multiwii_python#4]
I added a couple of prints so i could try and figure out what it's doing. and i'm getting exceptions. I'm new to the MSP protocol and i'm working with 2.1 of inav which apparently uses the v2 version of MSP.

I'm trying to get GPS data from the FC that's all i'm really interested in. So right now the main looks like the following:

i'm assuming the "container" section is the reply from the FC to the IDENT? When I tried the program unmodified, i got the exception in the second code section (under the dashes). 

Any help would be appreciated in getting at the GPS data

```
if __name__ == '__main__':
    transport = Serial(port='/dev/ttyACM0',
                       baudrate=115200,
                       timeout=5)
    msp = MSP(transport, initialization_delay=15)

    stop_gps_updates(msp)

    print("Getting IDENT")
    print(msp.request(MSP_IDENT))


    counter = 0
    print("Getting RAW_GPS")
    while True:
         print(counter)
         print(msp.receive_data(msp.get_response(MSP_RAW_GPS)))
         print(msp.request(MSP_ALTITUDE))
         counter += 1
         time.sleep(1)
```

```
Waiting 15 seconds for board to wake up
Done waiting
Sending MSP len 10
Getting IDENT
Sending MSP len 6
Container:
    preamble = b'$M' (total 2)
    direction = b'>' (total 1)
    size = 7
    message_id = 100
    version = 231
    multitype = 3
    msp_version = 0
    capability = 2147483708
    crc = 59
Getting RAW_GPS
0
Attempted to parse b''
Traceback (most recent call last):
  File "msp.py", line 327, in <module>
    print(msp.receive_data(msp.get_response(MSP_RAW_GPS)))
  File "msp.py", line 293, in receive_data
    return self.parse(received_data, parser)
  File "msp.py", line 275, in parse
    parsed_data = template.parse(data)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 304, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 316, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 2538, in _parse
    obj = self.subcon._parsereport(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 856, in _parse
    return stream_read(stream, length)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 86, in stream_read
    raise StreamError("stream read less then specified amount, expected %d, found %d" % (length, len(data)))
construct.core.StreamError: stream read less then specified amount, expected 2, found 0
```

-------------------------------------------------
```
charlesb@GroundStation:~/src/msp/multiwii_python$ python3 msp.py
Waiting 15 seconds for board to wake up
Done waiting
Sending MSP len 10
Sending MSP len 6
Container:
    preamble = b'$M' (total 2)
    direction = b'>' (total 1)
    size = 7
    message_id = 100
    version = 231
    multitype = 3
    msp_version = 0
    capability = 2147483708
    crc = 59
0
Drop flotation device (timed)
Sending MSP len 7
Attempted to parse b'$M>H4\x00'
Traceback (most recent call last):
  File "msp.py", line 364, in <module>
    msp.read_ack(MSP_SET_RC_OVERRIDES)
  File "msp.py", line 251, in read_ack
    ack = self.receive_data(MSP_ACK)
  File "msp.py", line 293, in receive_data
    return self.parse(received_data, parser)
  File "msp.py", line 275, in parse
    parsed_data = template.parse(data)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 304, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 316, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 2540, in _parse
    raise ConstError("parsing expected %r but parsed %r" % (self.value, obj))
construct.core.ConstError: parsing expected 0 but parsed 72
```

**Comment by andreiciubotariu** [comment]
You're most likely seeing errors because `main` is testing a special fork of the MultiWii 2.4 firmware. The changes are behavioural, and do not affect the MSP structure, but the following
```
stop_gps_updates(msp)
print(msp.receive_data(msp.get_response(MSP_RAW_GPS)))
MSP_SET_RC_OVERRIDES
MSP_GET_RC_OVERRIDES
MSP_GPS_REPORT_INTERVAL
MSP_PERIODIC_GPS_REPORT
```

work on custom behaviour. The normal MSP does not behave this way.

Anyway, to answer your question:

> i'm assuming the "container" section is the reply from the FC to the IDENT? 

Yeah. Specifically, it is the string representation of the `construct` python lib's `Struct` object that was decoded from the bytes received. I think it's a decent human-readable representation

------
Now, to get GPS updates, you should instead use 
```
msp.request(MSP_RAW_GPS)
```

This takes care of both sending the request to the FC, and reading its response.

However I've never worked with iNav so I'm not sure if they've changed anything else

**Comment by wx4cb** [comment]
here's the ONLY documentation from the inav team on the msp stuff. and of course i tried asking in their github and got told where to go basically... (btw im still waiting for an answer on FB and telegram lol)

https://github.com/iNavFlight/inav/issues/4465

there is nowhere in the wiki other than these two pages (which describe the frames and inav specific changes) that describe the MSP V2 protocol.

https://github.com/iNavFlight/inav/wiki/MSP-Navigation-Messages
https://github.com/iNavFlight/inav/wiki/INAV-MSP-frames-changelog

**Comment by wx4cb** [comment]
so this is what I have at the minute. sometimes it works sometimes it doesnt

```
if __name__ == '__main__':
    transport = Serial(port='/dev/rfcomm0',
                       baudrate=115200,
                       timeout=5)
    msp = MSP(transport, initialization_delay=5)

    stop_gps_updates(msp)

    print("Getting IDENT")
    print(msp.request(MSP_IDENT))


    counter = 0
    while True:
        print(counter)
        print("Getting NAV_STATUS")
        print(msp.request(MSP_NAV_STATUS))
        counter += 1
        time.sleep(1)
```

**Comment by wx4cb** [comment]
```
this is the result of running that in the previous comment:

charlesb@GroundStation:~/src/msp/multiwii_python$ python3 msp.py
Waiting 5 seconds for board to wake up
Done waiting
Sending MSP len 10
Getting IDENT
Sending MSP len 6
Attempted to parse b'$M>\x07d\xe7\x03\x00<'
Traceback (most recent call last):
  File "msp.py", line 320, in <module>
    print(msp.request(MSP_IDENT))
  File "msp.py", line 297, in request
    return self.receive_data(self.get_response(message_id))
  File "msp.py", line 293, in receive_data
    return self.parse(received_data, parser)
  File "msp.py", line 275, in parse
    parsed_data = template.parse(data)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 304, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 316, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 1028, in _parse
    data = stream_read(stream, self.length)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 86, in stream_read
    raise StreamError("stream read less then specified amount, expected %d, found %d" % (length, len(data)))
construct.core.StreamError: stream read less then specified amount, expected 4, found 1
charlesb@GroundStation:~/src/msp/multiwii_python$ python3 msp.py
Waiting 5 seconds for board to wake up
Done waiting
Sending MSP len 10
Getting IDENT
Sending MSP len 6
Container:
    preamble = b'$M' (total 2)
    direction = b'>' (total 1)
    size = 7
    message_id = 100
    version = 231
    multitype = 3
    msp_version = 0
    capability = 2147483708
    crc = 59
0
Getting NAV_STATUS
Sending MSP len 6
Container:
    preamble = b'$M' (total 2)
    direction = b'>' (total 1)
    size = 7
    message_id = 121
    gps_mode = 0
    nav_state = 0
    curr_mission_action = 0
    curr_mission_number = 1
    nav_error = 0
    target_bearing = 47
    crc = 80
1
Getting NAV_STATUS
Sending MSP len 6
Container:
    preamble = b'$M' (total 2)
    direction = b'>' (total 1)
    size = 7
    message_id = 121
    gps_mode = 0
    nav_state = 0
    curr_mission_action = 0
    curr_mission_number = 1
    nav_error = 0
    target_bearing = 47
    crc = 80
2
Getting NAV_STATUS
Sending MSP len 6

*********** pause about 5 seconds **********

Attempted to parse b'$M>\x07y\x00\x00\x00\x01'
Traceback (most recent call last):
  File "msp.py", line 329, in <module>
    print(msp.request(MSP_NAV_STATUS))
  File "msp.py", line 297, in request
    return self.receive_data(self.get_response(message_id))
  File "msp.py", line 293, in receive_data
    return self.parse(received_data, parser)
  File "msp.py", line 275, in parse
    parsed_data = template.parse(data)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 304, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 316, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 1028, in _parse
    data = stream_read(stream, self.length)
  File "/home/charlesb/.local/lib/python3.6/site-packages/construct/core.py", line 86, in stream_read
    raise StreamError("stream read less then specified amount, expected %d, found %d" % (length, len(data)))
construct.core.StreamError: stream read less then specified amount, expected 1, found 0
charlesb@GroundStation:~/src/msp/multiwii_python$
```

**Comment by andreiciubotariu** [comment]
Looks like your serial connection is dropping bytes or the FC is sending data too slowly sometimes. 

Try increasing the timeout from 5 seconds to something longer to fix the latter if it is the issue.

**Comment by wx4cb** [comment]
Ok ill check that out. I am running over bluetooth at 57600 via crossfire to the aircraft.

Im going to tey it via my laptop instead of on a pi.

That said diatance isn't an issue atm as theyre all right next to each other 

I did notice that i get the "sending xxx" and a out a 5 second delay for getting the ident

**Comment by wx4cb** [comment]
definitely seems like a crossfire/bluetooth thing. i'm running plugged into the FC right now and it kinda works -no gps data though still barfs on that. but i've also added a couple of other REQUEST setups in there which seem to work outside of it complaining about the crc

**Comment by andreiciubotariu** [comment]
Good to know. Closing this since the CRC works on MultiWii 2.4 which is my only priority right now.

**Comment by wx4cb** [comment]
that's np, is there a way to get it to ignore the CRC for now? I guess just comment out the crc check ?

**Comment by andreiciubotariu** [comment]
For receiving data: In `parse()` you can set the default value of `crc_data` to `False`.
For sending data, that's trickier as your FC expects a sane CRC. You could just rewrite `calc_crc`.
